### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by codeofsumit** [felixheck/wc2018-slack-bot#1]
when the bot is deployed for the first time, it should trigger a welcome message in the channel like "This is your goalie for today" or "welcome to the 2018 world cup" just to see if the connection from the bot to the slack channel works.

**Comment by codeofsumit** [comment]
![image](https://user-images.githubusercontent.com/2399810/41450954-cf74e5ca-706a-11e8-90d9-7624d7cb39c1.png)

**Comment by felixheck** [comment]
Thanks!
